### ISSUE TITLE
/home and /media should be accessible to export the library database

### ISSUE THREAD

**Issue by Wolpertinger** [flathub/de.haeckerfelix.gradio#1]
Currently it is not possible to save (or restore) the library database to the home folder or USB stick because these directories are not accessible.

**Comment by TingPing** [comment]
I'm not familiar with this feature but it should be using GtkFIleChooserNative, should be an easy patch (to upstream of course).

**Comment by haecker-felix** [comment]
The problem was that the application had no read/write permissions. I added the required permissions to the flatpak json. This should solve the problem for the home directory. (Without using the native Filechosser)

Anyway i should using the Native FileChooser soon...
