### ISSUE TITLE
gradio opens in background when openning any other app in flatpak???

### ISSUE THREAD

**Issue by pablodav** [flathub/de.haeckerfelix.gradio#6]
after using gradio for some time, I have got some automatic reproduction in background even when I set to not reproduce in background.

It happens after logon, when I open some other flatpak app or some times in unexpected times.

I hear the sound of the last radio openned but don't see gradio on any window, but if I go to process I see it openned there even when I haven't started the app....

Something completely unexpected.

**Comment by haecker-felix** [comment]
I guess you are using the GNOME Shell.

GNOME Control Center -> Search -> Untick Gradio.

Its a problem with GNOME Shell search.

**Comment by pablodav** [comment]
You are right, it is a good workaround.

I haven't found any issue related to this reported in gnome gitlab repos. Probably didn't look in correct place? do you know if there is any issue openned for gnome control centre/search/tracker?

**Comment by TingPing** [comment]
> GNOME Control Center -> Search -> Untick Gradio.
> Its a problem with GNOME Shell search.

How is that a GNOME-Shell bug?

**Comment by haecker-felix** [comment]
No, it's NOT a GNOME-Shell bug. It's a bug of Gradio.

If you search something, GNOME Shell starts Gradio for the search results. And here is the bug: If you enabled the option to continue your last playback, it will start.

**Comment by bilelmoussaoui** [comment]
This is not a Gradio flatpak specific bug anyway.
