### ISSUE TITLE
Why does gradio need --filesystem=host acess?

### ISSUE THREAD

**Issue by AdrianKoshka** [flathub/de.haeckerfelix.gradio#8]
I was wondering why this flatpak needs `--filesystem=host` access. That's a rather large portion of the sandbox to open. Gradio seems to run fine if you revoke `--filesystem=host` acess.

**Comment by haecker-felix** [comment]
You're right, there's no reason why Gradio should have access to everything. I have now limited access to "--filesystem=home".

Gradio needs acess to import/export the library.

**Comment by TingPing** [comment]
Ugh `host` -> `home` is a silly change. It only annoys users and doesn't in any way improve security.

> Gradio needs acess to import/export the library.

What exactly does the library refer to?

**Comment by haecker-felix** [comment]
@TingPing i know, it's better to use the flatpak FileChooser portal, than granting access to the complete home folder. I have to implement this.

> What exactly does the library refer to?

The library (which contains the radio stations) itself lies under "/home/user/.var/app/de.haeckerfelix.gradio/.../gradio.db", which is fine. However the user can export the library to somewhere else, or import it from somewhere else.

**Comment by AdrianKoshka** [comment]
Personal suggestion, no `--filesystem=home`, and instead maybe `--filesystem=xdg-downloads` to export/import the library to/from?

**Comment by TingPing** [comment]
Using GtkFileChooserNative is a very simple change. I suggest not worrying about permissions until that is implemented.

**Comment by haecker-felix** [comment]
Gradio uses GtkFileChooserNative now => We don't need require  "--filesystem=home" anymore.
