### ISSUE TITLE
Update to Gnome 3.32

### ISSUE THREAD

**Issue by x80486** [flathub/de.haeckerfelix.gradio#9]

**Comment by pablodav** [comment]
org.gnome.Platform is end-of-life, with reason: GNOME 3.24 runtime is no longer supported

Looks more update version is outside this repo:

https://github.com/haecker-felix/Gradio/blob/master/de.haeckerfelix.gradio.json

**Comment by go-ten** [comment]
Hi,
Is there any news on this request?
Thanks,

**Comment by bilelmoussaoui** [comment]
Already on 3.34
